### ISSUE TITLE
Running environment details

### ISSUE THREAD

**Issue by zhengyao11** [hustvl/GaussTR#2]
Hello, I really appreciate your great work. It merges foundation model, gaussian transformer and 3dgs into self supervised framework. Would you mind sharing the running environment details? Like versions of software and libraries.

**Comment by npurson** [comment]
Hi, thank you for your kind words and interest in our project! I think our project doesn’t rely on any specific version of python modules. Generally, I just installed the required dependencies using `pip install -r requirements.txt`. However, for PyTorch and gsplat, please refer to their official documentation to ensure compatibility with your specific CUDA version.

Feel free to reach out if you encounter any issues or need further assistance!

**Comment by zhengyao11** [comment]
Thank you. Actually, I am struggling with the versions of libraries, such as mmcv, mmdet, mmdet3d, mmsegmentatio. The functions and interfaces of different versions are different.

**Comment by npurson** [comment]
```
Package                 Version            Editable project location
----------------------- ------------------ ---------------------------------------------------
gsplat                  1.4.0+pt21cu118
mmcv                    2.1.0
mmdet                   3.3.0
mmdet3d                 1.4.0
mmengine                0.10.4
mmpretrain              1.2.0
mmsegmentation          1.2.2
numpy                   1.26.4
openmim                 0.3.9
torch                   2.1.2+cu118
torchvision             0.16.2+cu118
```
